controller_node:
  ros__parameters:
    use_sim_time: true
    controller_types: [dummy]
    dummy:
      rt_freq: 30.0 
      plugin: easynav_controller/DummyController
      cycle_time_nort: 0.01
      cycle_time_rt: 0.001

# localizer_node:
#   ros__parameters:
#     use_sim_time: true
#     localizer_types: [dummy]
#     dummy:
#       rt_freq: 50.0
#       freq: 5.0
#       reseed_freq: 1.0
#       plugin: easynav_navmap_localizer/AMCLLocalizer
#       num_particles: 200
#       noise_translation: 0.05
#       noise_rotation: 0.03
#       noise_translation_to_rotation: 0.01
#       min_noise_xy: 0.05
#       min_noise_yaw: 0.03
#       inflation_stddev: 0.15
#       compute_odom_from_tf: true 
#       initial_pose:
#         x: 0.0
#         y: 0.0
#         yaw: 0.0
#         std_dev_xy: 0.1
#         std_dev_yaw: 0.01

localizer_node:
  ros__parameters:
    use_sim_time: true
    localizer_types: [dummy]
    dummy:
      rt_freq: 50.0
      freq: 5.0
      reseed_freq: 1.0
      plugin: easynav_navmap_localizer/AMCLLocalizer
      num_particles: 100
      noise_translation: 0.1
      noise_rotation: 0.05
      noise_translation_to_rotation: 0.05
      min_noise_xy: 0.2
      min_noise_yaw: 0.03
      inflation_stddev: 1.0
      downsampled_cloud_size: 5.0
      compute_odom_from_tf: true 
      initial_pose:
        x: 0.0
        y: 0.0
        yaw: 0.0
        std_dev_xy: 0.1
        std_dev_yaw: 0.05

maps_manager_node:
  ros__parameters:
    use_sim_time: true
    map_types: [bonxai, navmap]
    bonxai:
      freq: 10.0 
      plugin: easynav_bonxai_maps_manager/BonxaiMapsManager
      package: easynav_indoor_testcase
      occmap_path_file: maps/home2.yaml
    navmap:
      freq: 10.0 
      plugin: easynav_navmap_maps_manager/NavMapMapsManager
      package: easynav_indoor_testcase
      occmap_path_file: maps/home2.yaml
# maps_manager_node:
#   ros__parameters:
#     use_sim_time: true
#     map_types: [bonxai, navmap]
#     bonxai:
#       freq: 10.0 
#       plugin: easynav_bonxai_maps_manager/BonxaiMapsManager
#       package: easynav_indoor_testcase
#       bonxai_path_file: maps/excavation_urjc.pcd
#     navmap:
#       freq: 10.0 
#       plugin: easynav_navmap_maps_manager/NavMapMapsManager
#       package: easynav_indoor_testcase
#       navmap_path_file: maps/excavation_urjc.navmap

#planner_node:
#  ros__parameters:
#    use_sim_time: true
#    planner_types: [dummy]
#    dummy:
#      freq: 1.0
#      plugin: easynav_planner/DummyPlanner
#      cycle_time_nort: 0.2
#      cycle_time_rt: 0.001

sensors_node:
  ros__parameters:
    use_sim_time: true
    forget_time: 0.5
    sensors: [laser]
    perception_default_frame: odom
    laser:
      topic: scan_raw
      type: sensor_msgs/msg/LaserScan

# sensors_node:
#   ros__parameters:
#     use_sim_time: true
#     forget_time: 0.5
#     sensors: [laser, camera, imu]
#     perception_default_frame: odom
#     laser:
#       topic: front_laser/points
#       type: sensor_msgs/msg/PointCloud2
#     camera:
#       topic: front_camera/depth/color/points
#       type: sensor_msgs/msg/PointCloud2
#     imu:
#       topic: imu/data
#       type: sensor_msgs/msg/Imu

system_node:
  ros__parameters:
    use_sim_time: true
    use_real_time: false
    position_tolerance: 0.3
    angle_tolerance: 0.15
