controller_node:
  ros__parameters:
    use_sim_time: true
    controller_types: [mppi]
    mppi:
      rt_freq: 30.0 
      plugin: easynav_mppi_controller/MPPIController
      num_samples: 200
      horizon_steps: 5
      dt: 0.15
      lambda: 1.0      
      fov: 1.57
      max_linear_velocity: 1.5
      max_angular_velocity: 1.0
      max_linear_acceleration: 0.5
      max_angular_acceleration: 0.5
      safety_radius: 0.3

localizer_node:
  ros__parameters:
    use_sim_time: true
    localizer_types: [costmap]
    costmap:
      rt_freq: 50.0
      freq: 5.0
      reseed_freq: 1.0
      plugin: easynav_costmap_localizer/AMCLLocalizer
      num_particles: 100
      noise_translation: 0.05
      noise_rotation: 0.1
      noise_translation_to_rotation: 0.1
      initial_pose:
        x: 0.0
        y: 0.1
        yaw: 0.0
        std_dev_xy: 0.1
        std_dev_yaw: 0.01

maps_manager_node:
  ros__parameters:
    use_sim_time: true
    map_types: [costmap, routes]
    routes:
      freq: 10.0 
      plugin: easynav_routes_maps_manager/RoutesMapsManager
      package: easynav_indoor_testcase
      map_path_file: maps/routes_1.yaml
      filters: [routes_costmap]
      routes_costmap:
        plugin: easynav_routes_maps_manager/RoutesCostmapFilter
        min_cost: 200
        route_width: 0.1
      cycle_time_nort: 0.001
      cycle_time_rt: 0.001
    costmap:
      freq: 10.0 
      plugin: easynav_costmap_maps_manager/CostmapMapsManager
      package: easynav_indoor_testcase
      map_path_file: maps/home2.yaml
      filters: [obstacles, inflation]
      obstacles:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/ObstaclesFilter
      inflation:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/InflationFilter
        inflation_radius: 0.8
        inscribed_radius: 0.25
        cost_scaling_factor: 3.0

planner_node:
  ros__parameters:
    use_sim_time: true
    planner_types: [simple]
    simple:
      freq: 0.5
      plugin: easynav_costmap_planner/CostmapPlanner
      cost_factor: 8.0
      heuristic_scale: 1.0
      continuous_replan: true

sensors_node:
  ros__parameters:
    use_sim_time: true
    forget_time: 0.5
    sensors: [laser1]
    perception_default_frame: odom
    laser1:
      topic: scan_raw
      type: sensor_msgs/msg/LaserScan
    camera1:
      topic: rgbd_camera/points
      type: sensor_msgs/msg/PointCloud2

system_node:
  ros__parameters:
    use_sim_time: true
    use_real_time: true
    position_tolerance: 0.3
    angle_tolerance: 0.15
