controller_node:
  ros__parameters:
    use_sim_time: true
    controller_types: [mpc]
    mpc:
      rt_freq: 30.0 
      plugin: easynav_mpc_controller/MPCController

localizer_node:
  ros__parameters:
    use_sim_time: true
    localizer_types: [lidarslam]
    lidarslam:
      plugin: easynav_lidarslam_localizer/LidarSlamLocalizer
      input_cloud: /front_laser/points
      imu: /imu/data

maps_manager_node:
  ros__parameters:
    use_sim_time: true
    map_types: [navmap]
    navmap:
      freq: 10.0 
      plugin: easynav_navmap_maps_manager/NavMapMapsManager
      package: easynav_indoor_testcase
      navmap_path_file: maps/excavation_urjc.navmap

planner_node:
  ros__parameters:
    use_sim_time: true
    planner_types: [astart]
    astart:
      freq: 1.0
      plugin: easynav_navmap_planner/AStarPlanner

sensors_node:
  ros__parameters:
    use_sim_time: true
    forget_time: 0.5
    sensors: [laser, imu, gps]
    perception_default_frame: odom
    laser:
      topic: front_laser/points
      type: sensor_msgs/msg/PointCloud2
    camera:
      topic: front_camera/depth/color/points
      type: sensor_msgs/msg/PointCloud2
    imu:
      topic: imu/data
      type: sensor_msgs/msg/Imu
    gps:
      topic: gps/fix
      type: sensor_msgs/msg/NavSatFix

system_node:
  ros__parameters:
    use_sim_time: true
    position_tolerance: 0.1
    angle_tolerance: 0.05

scan_matcher:
  ros__parameters:
    use_sim_time: True
    registration_method: "NDT"
    ndt_resolution: 2.0
    ndt_num_threads: 2
    gicp_corr_dist_threshold: 5.0
    trans_for_mapupdate: 1.5
    vg_size_for_input: 0.5
    vg_size_for_map: 0.2
    use_min_max_filter: true
    scan_min_range: 1.0
    scan_max_range: 200.0
    scan_period: 0.2
    map_publish_period: 15.0
    num_targeted_cloud: 20
    set_initial_pose: true
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_z: 0.0
    initial_pose_qx: 0.0
    initial_pose_qy: 0.0
    initial_pose_qz: 0.0
    initial_pose_qw: 1.0
    use_imu: false
    use_odom: false
    debug_flag: false

graph_based_slam:
    ros__parameters:
      use_sim_time: True
      registration_method: "NDT"
      ndt_resolution: 1.0
      ndt_num_threads: 2
      voxel_leaf_size: 0.2
      loop_detection_period: 3000
      threshold_loop_closure_score: 0.7
      distance_loop_closure: 100.0
      range_of_searching_loop_closure: 20.0
      search_submap_num: 2
      num_adjacent_pose_cnstraints: 5
      use_save_map_in_loop: true
      debug_flag: true
