// Copyright 2025 Intelligent Robotics Lab
//
// This file is part of the project Easy Navigation (EasyNav in short)
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// #pragma once
#ifndef EASYNAV_MPC_CONTROLLER__MPCCONTROLLER_HPP_
#define EASYNAV_MPC_CONTROLLER__MPCCONTROLLER_HPP_

#include <vector>
#include <Eigen/Core>
#include <nlopt.hpp>
#include <cmath>

#include <tf2/LinearMath/Quaternion.hpp>

#include "geometry_msgs/msg/pose.hpp"
#include "geometry_msgs/msg/pose_stamped.hpp"
#include "geometry_msgs/msg/twist_stamped.hpp"
#include "nav_msgs/msg/odometry.hpp"
#include "nav_msgs/msg/path.hpp"

#include <pcl/io/pcd_io.h>
#include <pcl_conversions/pcl_conversions.h>

#include "sensor_msgs/msg/point_cloud2.hpp"

#include "easynav_core/ControllerMethodBase.hpp"
#include "easynav_common/types/NavState.hpp"
#include "easynav_common/types/PointPerception.hpp"

#include "easynav_mpc_controller/MPCOptimizer.hpp"

namespace easynav
{

/// \brief A MPC Controller.
class MPCController : public ControllerMethodBase
{
public:
  MPCController();

  /// \brief Destructor.
  ~MPCController() override;

  /// \brief Initializes parameters and MPC controller.
  /// \throws std::runtime_error if initialization fails.
  void on_initialize() override;

  /// \brief Updates the controller using the given NavState.
  /// \param nav_state Current navigation state, including odometry and planned path.
  void update_rt(NavState & nav_state) override;

  /// \brief Publishes the selected path by MPC controller
  /// \param data MPCParameters object as data pointer
  /// \param best_path Vector of velocities generated by MPC
  /// \param path Path obtained from navstate
  void publish_mpc_path(
    void *data, const std::vector<double> & best_path,
    nav_msgs::msg::Path path);

  /// \brief Check if there is a possible collision
  /// \param data MPCParameters object as data pointer
  /// \param u Vector of velocities generated by MPC
  void collision_checker(void *data, std::vector<double> & u);

protected:
  int horizon_steps_{5};                ///< Prediction horizon for MPC.
  double dt_{0.1};                      ///< Time step for MPC.
  double safety_radius_{0.35};          ///< Safety radius to avoid obstacles
  double max_lin_vel_{1.5};             ///< Maximum linear velocity for MPC.
  double max_ang_vel_{1.5};             ///< Maximum angular velocity for MPC.
  bool verbose_{false};                 ///< Value to debug on terminal
  double last_v_{0.0};                  ///< Last value for linear velocity before than collision
  double last_w_{0.0};                  ///< Last value for angular velocity before than collision
  bool collision_state_{false};         ///< Collision state flag
  double collision_factor_{0.618033};   ///< Collision avoidance for recalculate velocities

  // Fallback goal tolerances if GoalManager does not publish them
  double fallback_goal_pos_tol_{0.05};   ///< Default positional tolerance (meters).
  double fallback_goal_yaw_tol_{0.05};   ///< Default angular tolerance (radians).

  std::unique_ptr<MPCOptimizer> optimizer_;  ///< MPC optimizer

  rclcpp::Publisher<nav_msgs::msg::Path>::SharedPtr mpc_path_pub_;            ///< Publisher for MPC path.
  rclcpp::Publisher<sensor_msgs::msg::PointCloud2>::SharedPtr detection_pub_; ///< Publisher for MPC obstacles.

private:
  geometry_msgs::msg::TwistStamped cmd_vel_;  ///< Current velocity command.

};

}  // namespace easynav

#endif  // EASYNAV_MPC_CONTROLLER__MPCCONTROLLER_HPP_
