# rutas
controller_node:
  ros__parameters:
    use_sim_time: false
    colision_checker:
      active: true
      debug_markers: true
      downsample_leaf_size: 0.05
      robot_radius: 0.30
      brake_acc: 1.0
      safety_margin: 0.10
    controller_types: [serest]
    serest:
      rt_freq: 10.0 #cambiado de 30.0 a 10 para mejorar la frecuencia de actualización del controlador
      plugin: easynav_serest_controller/SerestController
      allow_reverse: true
      max_linear_speed: 0.5
      max_angular_speed: 0.5
      v_progress_min: 0.08        # 8 cm/s de crucero mínimo cuando alineado
      k_s_share_max: 0.5          # succión lateral no cancela >50% del avance
      k_theta: 2.5                # sube un poco
      k_y: 1.5
      goal_pos_tol: 0.3          # 7 cm
      goal_yaw_tol_deg: 45.0       # 6 grados
      slow_radius: 0.60
      slow_min_speed: 0.03
      final_align_k: 1.0
      final_align_wmax: 0.3
      corner_guard_enable: true
      corner_gain_ey: 1.8
      corner_gain_eth: 0.7
      corner_gain_kappa: 0.4
      corner_min_alpha: 0.35
      corner_boost_omega: 1.0
      a_lat_soft: 0.9
      apex_ey_des: 0.05

localizer_node:
  ros__parameters:
    use_sim_time: false
    localizer_types: [costmap]
    costmap:
      rt_freq: 30.0 #cambiado de 50.0 a 15 para mejorar la frecuencia de actualización del mapa de partículas
      freq: 2.0
      reseed_freq: 1.0
      plugin: easynav_costmap_localizer/AMCLLocalizer
      num_particles: 100
      noise_translation: 0.05
      noise_rotation: 0.1
      noise_translation_to_rotation: 0.1
      initial_pose:
        x: 9.5
        y: 10.5
        yaw: 0.0
        std_dev_xy: 0.1
        std_dev_yaw: 0.01

maps_manager_node:
  ros__parameters:
    use_sim_time: false
    map_types: [costmap, routes]
    routes:
      freq: 2.0
      plugin: easynav_routes_maps_manager/RoutesMapsManager
      package: fwmini
      map_path_file: routes/routes.yaml
      filters: [routes_costmap]
      routes_costmap:
        plugin: easynav_routes_maps_manager/RoutesCostmapFilter
        min_cost: 50
        route_width: 0.1
      cycle_time_nort: 0.001
      cycle_time_rt: 0.001
    costmap:
      freq: 2.0
      plugin: easynav_costmap_maps_manager/CostmapMapsManager
      package: fwmini
      map_path_file: maps/mapa_ai2_tfg.yaml
      filters: [obstacles, inflation]
      obstacles:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/ObstaclesFilter
      inflation:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/InflationFilter
        inflation_radius: 0.6 #cuanto se expande el costo alrededor de los obstáculos
        inscribed_radius: 0.3 #radio del robot, dentro de este radio el costo es máximo
        cost_scaling_factor: 1.0 #cuánto se reduce el costo por cada celda adicional de distancia desde el obstáculo (costo = exp(-cost_scaling_factor * (distance - inscribed_radius)))

planner_node:
  ros__parameters:
    use_sim_time: false
    planner_types: [simple]
    simple:
      freq: 0.5
      plugin: easynav_costmap_planner/CostmapPlanner
      cost_factor: 10.0
      continuous_replan: false #cambiado a false para evitar que el planificador intente replanificar constantemente debido a pequeñas variaciones en la posición estimada por el localizador

sensors_node:
  ros__parameters:
    use_sim_time: false
    forget_time: 0.5
    sensors: [laser1]
    laser1:
      topic: scan
      type: sensor_msgs/msg/LaserScan

system_node:
  ros__parameters:
    use_sim_time: false
    use_real_time: true
    position_tolerance: 0.4
    angle_tolerance: 0.3
