controller_node:
  ros__parameters:
    use_sim_time: false
    controller_types: [mppi]
    colision_checker:
      active: true
      debug_markers: true
      downsample_leaf_size: 0.05
      robot_radius: 0.30
      brake_acc: 1.0     
      safety_margin: 0.10  
    mppi:
      rt_freq: 10.0 
      plugin: easynav_mppi_controller/MPPIController
      num_samples: 200
      horizon_steps: 15         # aumentado de 5 a 12 para mejor previsión (1.8s adelante)
      lambda: 1.0      
      fov: 1.57
      max_linear_velocity: 0.5
      max_angular_velocity: 0.5
      max_linear_acceleration: 0.5
      max_angular_acceleration: 0.5
      safety_radius: 0.20

localizer_node:
  ros__parameters:
    use_sim_time: false
    localizer_types: [costmap]
    costmap:
      rt_freq: 30.0
      freq: 2.0
      reseed_freq: 1.0
      plugin: easynav_costmap_localizer/AMCLLocalizer
      num_particles: 100
      noise_translation: 0.05
      noise_rotation: 0.1
      noise_translation_to_rotation: 0.1
      initial_pose:
        x: 0.0
        y: 0.1
        yaw: 0.0
        std_dev_xy: 0.1
        std_dev_yaw: 0.01

maps_manager_node:
  ros__parameters:
    use_sim_time: false
    map_types: [costmap]
    costmap:
      freq: 2.0 
      plugin: easynav_costmap_maps_manager/CostmapMapsManager
      package: fwmini
      map_path_file: maps/mapa_ai2_tfg.yaml
      filters: [obstacles, inflation]
      obstacles:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/ObstaclesFilter
      inflation:
        plugin: easynav_costmap_maps_manager/CostmapMapsManager/InflationFilter
        inflation_radius: 0.6
        inscribed_radius: 0.3
        cost_scaling_factor: 2.0

planner_node:
  ros__parameters:
    use_sim_time: true
    planner_types: [simple]
    simple:
      freq: 10.0
      plugin: easynav_costmap_planner/CostmapPlanner
      cost_factor: 10.0
      continuous_replan: true

sensors_node:
  ros__parameters:
    use_sim_time: true
    forget_time: 0.5
    sensors: [laser1]
    perception_default_frame: odom
    laser1:
      topic: scan
      type: sensor_msgs/msg/LaserScan

system_node:
  ros__parameters:
    use_sim_time: true
    use_real_time: true
    position_tolerance: 0.4
    angle_tolerance: 0.3
