controller_node:
  ros__parameters:
    use_sim_time: false
    controller_types: [dummy]
    dummy:
      rt_freq: 30.0
      plugin: easynav_controller/DummyController
      cycle_time_nort: 0.01
      cycle_time_rt: 0.0001

localizer_node:
  ros__parameters:
    use_sim_time: false
    localizer_types: [gps]
    dummy:
      rt_freq: 10.0
      freq: 10.0
      plugin: easynav_localizer/DummyLocalizer
      cycle_time_nort: 0.01
      cycle_time_rt: 0.001
    gps:
      rt_freq: 5.0
      freq: 5.0
      plugin: easynav_gps_localizer/GpsLocalizer

maps_manager_node:
  ros__parameters:
    use_sim_time: false
    map_types: [dummy]
    dummy:
      freq: 10.0
      plugin: easynav_maps_manager/DummyMapsManager
      cycle_time_nort: 0.1
      cycle_time_rt: 0.0001

planner_node:
  ros__parameters:
    use_sim_time: false
    planner_types: [dummy]
    dummy:
      freq: 1.0
      plugin: easynav_planner/DummyPlanner
      cycle_time_nort: 0.2
      cycle_time_rt: 0.0001

# sensors_node:
#   ros__parameters:
#     use_sim_time: false
#     forget_time: 0.5
#     sensors: [imu, gps, laser1]
#     perception_default_frame: odom
#     imu:
#       topic: /fixposition/fpa/rawimu
#       type: sensor_msgs/msg/Imu
#     gps:
#       topic: /fixposition/odometry_llh
#       type: sensor_msgs/msg/NavSatFix
#     laser1:
#       topic: scan
#       type: sensor_msgs/msg/LaserScan

system_node:
  ros__parameters:
    use_sim_time: false
    position_tolerance: 0.1
    angle_tolerance: 0.05
