---
name: easynav
services:
  robot_description:
    image: easynav:jazzy
    build:
      context: ../..
      dockerfile: container/builder/Dockerfile
    privileged: true
    network_mode: "host"
    ipc: host
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=10
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - type: bind
        source: ../bags
        target: /home/ubuntu/bags

    command: >
      bash -c "source /opt/ros/jazzy/setup.bash &&
               source /home/ubuntu/ros_ws/install/setup.bash &&
               ros2 launch easynavigation robot_description.launch.py"
  scan:
    image: easynav:jazzy
    privileged: true
    network_mode: "host"
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=10
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: >
      bash -c "source /opt/ros/jazzy/setup.bash &&
               source /home/ubuntu/ros_ws/install/setup.bash &&
               ros2 launch easynavigation pointcloud_to_laserscan.launch.py"
  
  tf:
    image: easynav:jazzy
    privileged: true
    network_mode: "host"
    ipc: host
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=10
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - type: bind
        source: ../tfs
        target: /home/ubuntu/tfs
    command: >
      bash -c "source /opt/ros/jazzy/setup.bash &&
               source /home/ubuntu/ros_ws/install/setup.bash &&
               cd /home/ubuntu/ros_ws/src/easynavigation/src && 
               python3 broadcaster.py"
  map:
    image: easynav:jazzy
    privileged: true
    network_mode: "host"
    ipc: host
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=10
    volumes:
      - type: bind
        source: ../../src/fwmini/routes
        target: /home/ubuntu/ros_ws/src/fwmini/routes
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ["bash", "-c", "source /opt/ros/jazzy/setup.bash 
                && source /home/ubuntu/ros_ws/install/setup.bash
                && ros2 run easynav_system system_main --ros-args --params-file /home/ubuntu/ros_ws/src/fwmini/robots_params/costmap.serest.routed.params.yaml"]
  rviz:
    image: easynav:jazzy
    privileged: true
    network_mode: "host"
    ipc: host
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=10
    volumes:
      - type: bind
        source: ../rviz
        target: /home/ubuntu/rviz
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      bash -c "source /opt/ros/jazzy/setup.bash &&
               source /home/ubuntu/ros_ws/install/setup.bash &&
               rviz2 -d /home/ubuntu/rviz/rviz_config.rviz"

  remap:
    image: easynav:jazzy
    privileged: true
    network_mode: "host"
    ipc: host
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=10
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      bash -c "source /opt/ros/jazzy/setup.bash &&
               source /home/ubuntu/ros_ws/install/setup.bash &&
               ros2 run topic_tools relay /cmd_vel /cmd_vel_smoothed"
  foxglove:
   image: easynav:jazzy
   privileged: true
   network_mode: "host"
   ipc: host
   environment:
     - DISPLAY=$DISPLAY
     - QT_X11_NO_MITSHM=1
     - ROS_DOMAIN_ID=10
   depends_on:
     - robot_description
   volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix:rw
   command: ["bash", "-c", "source /opt/ros/jazzy/setup.bash \
               && source /home/ubuntu/ros_ws/install/setup.bash \
               && ros2 launch foxglove_bridge foxglove_bridge_launch.xml"]