cooldown: 300
conditions:
  - key: timed
    enabled: false
    name: Timed Snap
    tags: ["timed"]

  - key: lowConfidence
    enabled: false
    name: Low Confidence
    tags: ["confidence"]

  - key: noDetections
    enabled: false
    name: No Detections
    tags: ["no detections"]

  - key: lostMid
    enabled: false
    name: Lost in Middle
    tags: ["lost"]
