class_names: ["person", "chair", "TV"]
text_offset: 0
visual_offset: 80
max_num_classes: 80

quant_values:
  yoloe:
    quant_zero_point: 174.0
    quant_scale: 0.003328413470
  yoloe-image:
    quant_zero_point: 137.0
    quant_scale: 0.002327915514

paths:
  tokenizer:
    url: "https://huggingface.co/openai/clip-vit-base-patch32/resolve/main/tokenizer.json"
    path: "tokenizer.json"

  text_encoder:
    slug: "luxonis/yoloe-v8-l:mobileclip-textual-hf"
    path: "mobileclip_textual_hf.onnx"

  visual_encoder:
    slug: "luxonis/yoloe-v8-l:yoloe-v8l-seg-visual-encoder"
    path: "yoloe-v8l-seg_visual_encoder.onnx"