identifier = "example.apps.ros.follow-object"
app_version = "0.9.0"

prepare_container = [
    { type = "COPY", source = "resolv.conf", target = "/etc/resolv.conf" },
    { type = "RUN", command = "apt-get update -qq" },
    { type = "RUN", command = "apt install -y ros2-testing-apt-source"},
    { type = "RUN", command = "apt-get update -qq" },
    { type = "RUN", command = "apt-get install -qy ros-kilted-depthai-ros python3-colcon-common-extensions ros-kilted-teleop-twist-keyboard"},
]

prepare_build_container = [

]

build_steps = [
    "mkdir -p /ws/src",
    "cp -r /app/src/ /ws/",
    'bash -c "cd /ws && source /opt/ros/kilted/setup.bash && colcon build"'
]

entrypoint = ["bash", "-c", "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"]

[base_image]
api_url = "https://registry-1.docker.io" 
service = "registry.docker.io" 
oauth_url = "https://auth.docker.io/token"
auth_type = "repository" 
auth_name = "library/ros"
image_name = "library/ros"
image_tag = "kilted-ros-base"
