# ROS Humble Hawksbill (LTS until May 2027) base image (Ubuntu 22.04.6 LTS "Jammy")
FROM ros:humble-ros-base

# Metadata for github packages
LABEL org.opencontainers.image.description="Fixposition SDK docker image: ROS Humble (Ubuntu 22.04) base image with minimal stuff required to build"
LABEL org.opencontainers.image.source=https://github.com/fixposition

# Variables used in our Docker build and CI scripts
ENV FPSDK_IMAGE=humble-base
ENV ROS_DISTRO=humble

# Remove automatic use of /ros_entrypoint.sh, we'll deal with this ourselves
ENTRYPOINT []

# Install stuff
COPY docker/scripts/install_aptbase.sh /tmp
RUN /tmp/install_aptbase.sh && rm -f /tmp/install_aptbase.sh

# Download, build and install clang-format
COPY docker/scripts/install_clangformat.sh /tmp
RUN /tmp/install_clangformat.sh && rm -f /tmp/install_clangformat.sh

# Download, build and install googletest
COPY docker/scripts/install_gtest.sh /tmp
RUN /tmp/install_gtest.sh && rm -f /tmp/install_gtest.sh

# Download, build and install capnp (not currently used, though)
COPY docker/scripts/install_capnp.sh /tmp
RUN /tmp/install_capnp.sh && rm -f /tmp/install_capnp.sh

# Download, build and install PROJ
COPY docker/scripts/install_proj.sh /tmp
RUN /tmp/install_proj.sh && rm -f /tmp/install_proj.sh

# Download, build and install Doxygen
COPY docker/scripts/install_doxygen.sh /tmp
RUN /tmp/install_doxygen.sh && rm -f /tmp/install_doxygen.sh

# Update ld cache for the installed libraries
RUN /usr/sbin/ldconfig

# Prevent packages from installation that we build and installed above. Installing multiple versions of the same package
# can be tricky and we better prevent that from happening. It doesn't work for all packages, though. For example,
# ROS packages insist on libgtest.
COPY <<EOF /etc/apt/preferences.d/manually-built-and-installed
Package: clang-format clang-format-11 clang-format-12 clang-format-13 clang-format-14
Pin: origin *
Pin-Priority: -1

Package: capnproto libcapnp-* libcapnp-dev
Pin: origin *
Pin-Priority: -1

Package: proj proj-ps-doc proj-data proj-rdnap proj-bin libproj15 libproj-dev
Pin: origin *
Pin-Priority: -1
EOF

# For debugging docker builds... (last layer!)
RUN date > /fixposition-sdk-${FPSDK_IMAGE}
