FROM ghcr.io/fixposition/fixposition-sdk:noetic-base

LABEL org.opencontainers.image.description="Fixposition SDK docker image: ROS Noetic (Ubuntu 20.04) image for vscode devcontainer"
LABEL org.opencontainers.image.source=https://github.com/fixposition

ENV FPSDK_IMAGE=noetic-dev

# Unminimize system
COPY docker/scripts/unminimize_system.sh /tmp
RUN /tmp/unminimize_system.sh && rm -f /tmp/unminimize_system.sh

# Add user for devcontainer, see ../.devcontainer/devcontainer.json
COPY docker/scripts/adduser_fpsdk.sh /tmp
RUN /tmp/adduser_fpsdk.sh && rm -f /tmp/adduser_fpsdk.sh

# Install pre-commit hooks (fpsdk user)
COPY .pre-commit-config.yaml /tmp
COPY docker/scripts/install_precommithooks.sh /tmp
RUN sudo -u fpsdk /tmp/install_precommithooks.sh && rm -f /tmp/install_precommithooks.sh /tmp/.pre-commit-config.yaml

# Install git-bash-prompt (fpsdk user)
COPY .devcontainer/fpsdk.bgptheme /tmp
COPY docker/scripts/install_gitbashprompt.sh /tmp
RUN sudo -u fpsdk /tmp/install_gitbashprompt.sh && rm -f /tmp/install_gitbashprompt.sh /tmp/.devcontainer/fpsdk.bgptheme

# Set timezone, sane language and locale
ENV TZ=Europe/Zurich
ENV LANG=en_GB.UTF-8
ENV LANGUAGE=en_GB
ENV LC_ALL=C.UTF-8
COPY docker/scripts/install_locales.sh /tmp
RUN /tmp/install_locales.sh && rm -f /tmp/install_locales.sh

# Install yq
COPY docker/scripts/install_yq.sh /tmp
RUN /tmp/install_yq.sh && rm -f /tmp/install_yq.sh

# Install mcap
COPY docker/scripts/install_mcap.sh /tmp
RUN /tmp/install_mcap.sh && rm -f /tmp/install_mcap.sh

# Install useful stuff
COPY docker/scripts/install_aptdev.sh /tmp
RUN /tmp/install_aptdev.sh && rm -f /tmp/install_aptdev.sh

# For debugging docker builds... (last layer!)
RUN date > /fixposition-sdk-${FPSDK_IMAGE}
