FROM ghcr.io/fixposition/fixposition-sdk:bookworm-base

# Metadata for github packages
LABEL org.opencontainers.image.description="Fixposition SDK docker image: Debian Bookworm image for Github CI jobs"
LABEL org.opencontainers.image.source=https://github.com/fixposition

# Variables used in our Docker build and CI scripts
ENV FPSDK_IMAGE=bookworm-ci

# Install pre-commit hooks (root user)
COPY .pre-commit-config.yaml /tmp
COPY docker/scripts/install_precommithooks.sh /tmp
RUN /tmp/install_precommithooks.sh && rm -f /tmp/install_precommithooks.sh /tmp/.pre-commit-config.yaml

# Install useful stuff
COPY docker/scripts/install_aptci.sh /tmp
RUN /tmp/install_aptci.sh && rm -f /tmp/install_aptci.share

# For debugging docker builds... (last layer!)
RUN date > /fixposition-sdk-${FPSDK_IMAGE}
